#
# Copyright (C) 2022 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
build:
  quality:
    filter:
      owner: vaticle
      branch: [master, development]
    dependency-analysis:
      image: vaticle-ubuntu-22.04
      command: |
        bazel run @vaticle_dependencies//factory/analysis:dependency-analysis
  correctness:
    build:
      image: vaticle-ubuntu-22.04
      command: |
        bazel build //... --test_output=errors
        bazel run @vaticle_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=errors
    build-dependency:
      image: vaticle-ubuntu-22.04
      command: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @vaticle_dependencies//tool/unuseddeps:unused-deps -- list
    deploy-maven-snapshot:
      filter:
        owner: vaticle
        branch: [master, development]
      image: vaticle-ubuntu-22.04
      dependencies: [build]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //:deploy-maven -- snapshot
    sync-dependencies:
      image: vaticle-ubuntu-22.04
      filter:
        owner: vaticle
        branch: [master, development]
      dependencies: [deploy-maven-snapshot]
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @vaticle_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@${FACTORY_COMMIT}
release:
  filter:
    owner: vaticle
    branch: [master, development]
  deployment:
    deploy-github:
      image: vaticle-ubuntu-22.04
      command: |
        export NOTES_CREATE_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @vaticle_dependencies//tool/release/notes:create -- $FACTORY_OWNER $FACTORY_REPO $FACTORY_COMMIT $(cat VERSION) ./RELEASE_TEMPLATE.md ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $FACTORY_COMMIT
    deploy-maven-release:
      image: vaticle-ubuntu-22.04
      dependencies: [deploy-github]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run --define version=$(cat VERSION) //:deploy-maven -- release
    sync-dependencies-release:
      image: vaticle-ubuntu-22.04
      filter:
        owner: vaticle
        branch: [master, development]
      dependencies: [deploy-github, deploy-maven-release]
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @vaticle_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@$(cat VERSION)
