define

title sub attribute,
  value string;

event-date sub attribute,
  abstract,
  value datetime;
approved-date sub event-date;

## an abstract relation, only to be subtyped by other relations
request sub relation,
  abstract,
  owns approved-date,
  relates approved-subject,
  relates requester,
  relates respondent;

friendship sub relation,
    relates friend,
    plays friend-request:approved-friendship,
    plays friends-list:listed-friendship;

## an example of subtyping in Grakn
friend-request sub request,
    relates approved-friendship as approved-subject,
    relates friendship-requester as requester,
    relates friendship-respondent as respondent;

friends-list sub relation,
    owns title,
    relates list-owner,
    relates listed-friendship;

person sub entity,
    plays friendship:friend,
    plays friend-request:friendship-requester,
    plays friend-request:friendship-respondent,
    plays friends-list:list-owner;